/**
 * Generated TypeScript client from OpenAPI specification.
 * DO NOT EDIT MANUALLY. Generated by tools/gen_api_client.mjs
 */

export interface Counts {
  learning: number;
  new: number;
  review: number;
}

export interface Deck {
  children: Deck[];
  counts: Counts;
  filtered: boolean;
  id: number;
  name: string;
  path: string;
}

export interface DeckDetailBody {
  counts: Counts;
  deck: Deck;
  description: string;
}

export interface DeckList {
  counts: Counts;
  decks: Deck[];
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface LoginBody {
  password: string;
}

export interface SessionInfo {
  authRequired: boolean;
  authenticated: boolean;
  capabilities: string[];
  user: User;
}

export interface Status {
  status: string;
}

export interface User {
  id: string;
}

export interface ValidationError {
  ctx?: Record<string, unknown>;
  input?: unknown;
  loc: (string | number)[];
  msg: string;
  type: string;
}

export interface Paths {
  "/api/v1/auth/login": {
    post: {
      parameters: never;
      requestBody: LoginBody;
      response: void;
    };
  };
  "/api/v1/auth/logout": {
    post: {
      parameters: never;
      requestBody: never;
      response: void;
    };
  };
  "/api/v1/decks": {
    get: {
      parameters: never;
      requestBody: never;
      response: DeckList;
    };
  };
  "/api/v1/decks/{deck_id}": {
    get: {
      parameters: { path: { deck_id: number; } };
      requestBody: never;
      response: DeckDetailBody;
    };
  };
  "/api/v1/health/live": {
    get: {
      parameters: never;
      requestBody: never;
      response: Status;
    };
  };
  "/api/v1/health/ready": {
    get: {
      parameters: never;
      requestBody: never;
      response: Status;
    };
  };
  "/api/v1/session": {
    get: {
      parameters: never;
      requestBody: never;
      response: SessionInfo;
    };
  };
}

export class ApiError extends Error {
  public status: number;
  public detail: unknown;

  constructor(status: number, detail: unknown, message?: string) {
    const msg =
      message ||
      (typeof detail === "string"
        ? detail
        : detail && typeof detail === "object" && "detail" in detail
        ? typeof (detail as any).detail === "string"
          ? (detail as any).detail
          : JSON.stringify((detail as any).detail)
        : `HTTP ${status}`);
    super(msg);
    this.name = "ApiError";
    this.status = status;
    this.detail = detail;
  }
}

export interface ApiClient {
  login(body: LoginBody): Promise<void>;
  login_api_v1_auth_login_post(body: LoginBody): Promise<void>;
  logout(): Promise<void>;
  logout_api_v1_auth_logout_post(): Promise<void>;
  listDecks(): Promise<DeckList>;
  list_decks_api_v1_decks_get(): Promise<DeckList>;
  getDeck(deck_id: number): Promise<DeckDetailBody>;
  get_deck_api_v1_decks__deck_id__get(deck_id: number): Promise<DeckDetailBody>;
  live(): Promise<Status>;
  live_api_v1_health_live_get(): Promise<Status>;
  ready(): Promise<Status>;
  ready_api_v1_health_ready_get(): Promise<Status>;
  session(): Promise<SessionInfo>;
  session_api_v1_session_get(): Promise<SessionInfo>;
}

export function createClient(baseUrl: string = "", fetchImpl?: typeof fetch): ApiClient {
  const base = baseUrl.replace(/\/+$/, "");
  const _fetch =
    fetchImpl ||
    (typeof fetch !== "undefined"
      ? fetch.bind(globalThis)
      : (globalThis as any).fetch);

  async function request<T>(
    path: string,
    method: string,
    body?: unknown
  ): Promise<T> {
    const url = `${base}${path}`;
    const headers: Record<string, string> = {};
    const init: RequestInit = {
      method,
      credentials: "same-origin",
      headers,
    };

    if (body !== undefined) {
      headers["Content-Type"] = "application/json";
      init.body = JSON.stringify(body);
    }

    const response = await _fetch(url, init);

    if (!response.ok) {
      let detail: unknown;
      try {
        detail = await response.json();
      } catch {
        try {
          detail = await response.text();
        } catch {
          detail = null;
        }
      }
      throw new ApiError(response.status, detail);
    }

    if (response.status === 204) {
      return undefined as T;
    }

    const text = await response.text();
    if (!text) {
      return undefined as T;
    }

    try {
      return JSON.parse(text) as T;
    } catch {
      return text as unknown as T;
    }
  }

  const client: ApiClient = {
    login: (body: LoginBody) => request<void>("/api/v1/auth/login", "POST", body),
    login_api_v1_auth_login_post: (body: LoginBody) => request<void>("/api/v1/auth/login", "POST", body),
    logout: () => request<void>("/api/v1/auth/logout", "POST"),
    logout_api_v1_auth_logout_post: () => request<void>("/api/v1/auth/logout", "POST"),
    listDecks: () => request<DeckList>("/api/v1/decks", "GET"),
    list_decks_api_v1_decks_get: () => request<DeckList>("/api/v1/decks", "GET"),
    getDeck: (deck_id: number) => request<DeckDetailBody>(`/api/v1/decks/${encodeURIComponent(String(deck_id))}`, "GET"),
    get_deck_api_v1_decks__deck_id__get: (deck_id: number) => request<DeckDetailBody>(`/api/v1/decks/${encodeURIComponent(String(deck_id))}`, "GET"),
    live: () => request<Status>("/api/v1/health/live", "GET"),
    live_api_v1_health_live_get: () => request<Status>("/api/v1/health/live", "GET"),
    ready: () => request<Status>("/api/v1/health/ready", "GET"),
    ready_api_v1_health_ready_get: () => request<Status>("/api/v1/health/ready", "GET"),
    session: () => request<SessionInfo>("/api/v1/session", "GET"),
    session_api_v1_session_get: () => request<SessionInfo>("/api/v1/session", "GET"),
  };

  return client;
}
